language: node_js
node_js:
  - lts/*

branches:
  only:
  - master

install: yarn install

script: yarn test && yarn package

before_deploy: cd dist

deploy:
  skip_cleanup: true
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_API_KEY
  on:
      branch: master
      tags: true
