sudo: required
dist: trusty
addons:
  chrome: stable
language: node_js
node_js:
  - lts/*
branches:
  only:
    tags:
      - all
    - master
install: yarn install
script: yarn test --single-run= true --watch=false && yarn package
before_deploy: cd dist
deploy:
  skip_cleanup: true
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_API_KEY
  on:
      branch: master
      tags: true
