version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.3-browsers

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn lint
      - run: yarn test --single-run= true --watch=false

      - run: yarn package

      - store_artifacts:
          path: dist

      - persist_to_workspace:
          root: ~/repo
          paths:
            - dist

  deploy:
    docker:
      - image: circleci/node:8.11.3-browsers

    steps:
      - attach_workspace:
          at: /tmp/workspace

      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: cd /tmp/workspace/dist && npm publish

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
